services:
  auth:
    build:
      context: .
      dockerfile: "./apps/auth/Dockerfile"
      target: development
    command: npm run start:dev auth
    volumes:
      - .:/usr/src/app
      - "/usr/src/app/node_modules"
    depends_on:
      - rabbitmq
      - redis

  providers:
    build:
      context: .
      dockerfile: "./apps/providers/Dockerfile"
      target: development
    command: npm run start:dev providers
    volumes:
      - .:/usr/src/app
      - "/usr/src/app/node_modules"
    depends_on:
      - rabbitmq
      - redis

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  rabbitmq_data:
  redis_data: