variable "rg_name" {}
variable "acr_name" {}
variable "container_app_env_name" {}
variable "database_url" {}
variable "twilio_account_sid" {}
variable "twilio_auth_token" {}
variable "twilio_messaging_service_sid" {}
variable "twilio_phone_number" {}
variable "auth_container" {}
variable "providers_container" {}
variable "rabbitmq_container" {}
variable "redis_container" {}
variable "storage_container" {}
variable "auth_image" {}
variable "providers_image" {}
variable "rabbitmq_image" {}
variable "storage_image" {}
variable "redis_image" {}
variable "redis_host" {}
variable "rabbitmq_host" {}
variable "xpi_base_url" {}
variable "AZURE_STORAGE_CONNECTION_STRING" {}
